title: Movie List
title_separator: "|"
email: pylypchuk.tolik@gmail.com
description: An application for keeping a list of movies and series
baseurl: MovieList
github_username:  TolikPylypchuk
repository: TolikPylypchuk/MovieList

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed

search: true

collections:
  v0_1:
    output: true
    permalink: /v0.1/:path/

defaults:
  -
    scope:
      path: ""
      type: "v0_1"
    values:
      layout: single
      sidebar:
        nav: "v0_1"
      toc: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/TolikPylypchuk
